[theme]
base="dark"
backgroundColor="#272727"
primaryColor="#f9f9f9"
# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"

[ui]
hideTopBar=true

[global]
developmentMode=false

[client]
toolbarMode = "minimal"
