[theme]
base="dark"
backgroundColor="#272727"
primaryColor="#f9f9f9"
font = "sans serif"

[ui]
hideTopBar=true

[global]
developmentMode=false

[client]
toolbarMode = "minimal"

[server]
baseUrlPath = "/tv"

[browser]
gatherUsageStats = false
